services:
    _defaults:
        autoconfigure: true
        autowire: true

    DaybreakStudios\DoctrineQueryDocument\QueryManagerInterface: '@DaybreakStudios\DoctrineQueryDocument\QueryManager'
    DaybreakStudios\DoctrineQueryDocument\QueryManager:
        bind:
            $objectManager: '@doctrine.orm.default_entity_manager'

    DaybreakStudios\Rest\Response\ResponseBuilderInterface: '@DaybreakStudios\Rest\Response\ResponseBuilder'
    DaybreakStudios\Rest\Response\ResponseBuilder:
        bind:
            $serializer: '@app.serializer'

    DaybreakStudios\Rest\Event\Listeners\DefaultRequestFormatProvider: ~
    DaybreakStudios\Rest\Event\Listeners\Controller\PayloadInitListener: ~
    DaybreakStudios\Rest\Event\Listeners\Controller\PayloadInitValidationListener: ~
    DaybreakStudios\Rest\Event\Listeners\Controller\ProjectionInitListener: ~
    DaybreakStudios\Rest\Event\Listeners\Controller\QueryInitListener: ~
    DaybreakStudios\Rest\Event\Listeners\Controller\QueryLimitInitListener: ~
    DaybreakStudios\Rest\Event\Listeners\Controller\QueryOffsetInitListener: ~
    DaybreakStudios\Rest\Event\Listeners\ErrorExceptionListener: ~
