services:
    _defaults:
        autoconfigure: true
        autowire: true

    app.serializer:
        class: Symfony\Component\Serializer\Serializer
        arguments:
            -
                - '@serializer.denormalizer.array'
                - '@serializer.normalizer.datetime'
                - '@serializer.normalizer.backed_enum'
                - '@serializer.normalizer.problem'
                - '@DaybreakStudios\Rest\Serializer\EntityDenormalizer'
                - '@DaybreakStudios\Rest\Serializer\ObjectNormalizer'
            -
                - '@serializer.encoder.json'
                - '@serializer.encoder.csv'
                - '@serializer.encoder.xml'
                - '@serializer.encoder.yaml'

    DaybreakStudios\Rest\Serializer\ObjectNormalizer:
        bind:
            $objectNormalizer: '@serializer.normalizer.object'

    DaybreakStudios\Rest\Serializer\EntityDenormalizer: ~
