<?php
	declare(strict_types=1);

	namespace DoctrineMigrations;

	use Doctrine\DBAL\Schema\Schema;
	use Doctrine\Migrations\AbstractMigration;

	final class Version20250131021234 extends AbstractMigration {
		public function getDescription(): string {
			return 'Initial database state';
		}

		public function up(Schema $schema): void {
			// @formatter:off
			$this->addSql('CREATE TABLE ailment_protections (id INT UNSIGNED AUTO_INCREMENT NOT NULL, ailment_id INT UNSIGNED DEFAULT NULL, UNIQUE INDEX UNIQ_6630DD52432CD43A (ailment_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE ailment_protection_skills (ailment_protection_id INT UNSIGNED NOT NULL, skill_id INT UNSIGNED NOT NULL, INDEX IDX_517E18BFFE812F5B (ailment_protection_id), INDEX IDX_517E18BF5585C142 (skill_id), PRIMARY KEY(ailment_protection_id, skill_id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE ailment_protection_item (ailment_protection_items INT UNSIGNED NOT NULL, item_id INT UNSIGNED NOT NULL, INDEX IDX_84E874CF1051F85E (ailment_protection_items), INDEX IDX_84E874CF126F525E (item_id), PRIMARY KEY(ailment_protection_items, item_id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE ailment_recoveries (id INT UNSIGNED AUTO_INCREMENT NOT NULL, ailment_id INT UNSIGNED DEFAULT NULL, actions JSON NOT NULL COMMENT \'(DC2Type:json)\', UNIQUE INDEX UNIQ_712E946B432CD43A (ailment_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE ailment_recovery_items (ailment_recovery_id INT UNSIGNED NOT NULL, item_id INT UNSIGNED NOT NULL, INDEX IDX_400DCBFE8B04118A (ailment_recovery_id), INDEX IDX_400DCBFE126F525E (item_id), PRIMARY KEY(ailment_recovery_id, item_id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE ailments (id INT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE armor_crafting (id INT UNSIGNED AUTO_INCREMENT NOT NULL, armor_id INT UNSIGNED DEFAULT NULL, zenny_cost INT UNSIGNED NOT NULL, UNIQUE INDEX UNIQ_4BFD47B3F5AA3663 (armor_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE armor_crafting_costs (armor_crafting_id INT UNSIGNED NOT NULL, material_cost_id INT UNSIGNED NOT NULL, INDEX IDX_5B6BF2EDDD6DD251 (armor_crafting_id), INDEX IDX_5B6BF2EDAC255ED0 (material_cost_id), PRIMARY KEY(armor_crafting_id, material_cost_id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE armor_set_bonus_ranks (id INT UNSIGNED AUTO_INCREMENT NOT NULL, bonus_id INT UNSIGNED DEFAULT NULL, skill_id INT UNSIGNED DEFAULT NULL, pieces INT UNSIGNED NOT NULL, INDEX IDX_5DF784FC69545666 (bonus_id), INDEX IDX_5DF784FC5585C142 (skill_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE armor_set_bonuses (id INT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE armor_sets (id INT UNSIGNED AUTO_INCREMENT NOT NULL, bonus_id INT UNSIGNED DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, INDEX IDX_7C8A0B1069545666 (bonus_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE armors (id INT UNSIGNED AUTO_INCREMENT NOT NULL, armor_set_id INT UNSIGNED DEFAULT NULL, kind VARCHAR(255) NOT NULL, name VARCHAR(255) DEFAULT NULL, rank VARCHAR(255) NOT NULL, rarity INT UNSIGNED NOT NULL, slots JSON NOT NULL COMMENT \'(DC2Type:json)\', resist_fire INT NOT NULL, resist_water INT NOT NULL, resist_ice INT NOT NULL, resist_thunder INT NOT NULL, resist_dragon INT NOT NULL, defense_base INT UNSIGNED NOT NULL, defense_max INT UNSIGNED NOT NULL, defense_augmented INT UNSIGNED NOT NULL, INDEX IDX_AFBA56C2537E6F87 (armor_set_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE armor_skills (armor_id INT UNSIGNED NOT NULL, skill_rank_id INT UNSIGNED NOT NULL, INDEX IDX_96B474EFF5AA3663 (armor_id), INDEX IDX_96B474EF6CE3F9A6 (skill_rank_id), PRIMARY KEY(armor_id, skill_rank_id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE auto_reload (id INT UNSIGNED AUTO_INCREMENT NOT NULL, ammo VARCHAR(255) NOT NULL, level INT UNSIGNED NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE camps (id INT UNSIGNED AUTO_INCREMENT NOT NULL, location_id INT UNSIGNED DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, zone INT UNSIGNED NOT NULL, INDEX IDX_3D166BE564D218E (location_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE charm_rank_crafting (id INT UNSIGNED AUTO_INCREMENT NOT NULL, charm_rank_id INT UNSIGNED DEFAULT NULL, craftable TINYINT(1) NOT NULL, zenny_cost INT NOT NULL, UNIQUE INDEX UNIQ_15C9995D3BA5C9D1 (charm_rank_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE charm_rank_crafting_materials (charm_rank_crafting_id INT UNSIGNED NOT NULL, material_cost_id INT UNSIGNED NOT NULL, INDEX IDX_AC58A140401E3381 (charm_rank_crafting_id), INDEX IDX_AC58A140AC255ED0 (material_cost_id), PRIMARY KEY(charm_rank_crafting_id, material_cost_id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE charm_ranks (id INT UNSIGNED AUTO_INCREMENT NOT NULL, charm_id INT UNSIGNED DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, level INT UNSIGNED NOT NULL, rarity INT UNSIGNED NOT NULL, INDEX IDX_DF91C65593E9261F (charm_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE charm_rank_skills (charm_rank_id INT UNSIGNED NOT NULL, skill_rank_id INT UNSIGNED NOT NULL, INDEX IDX_6413356B3BA5C9D1 (charm_rank_id), INDEX IDX_6413356B6CE3F9A6 (skill_rank_id), PRIMARY KEY(charm_rank_id, skill_rank_id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE charms (id INT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE crafting_material_costs (id INT UNSIGNED AUTO_INCREMENT NOT NULL, item_id INT UNSIGNED DEFAULT NULL, quantity INT UNSIGNED NOT NULL, INDEX IDX_1B8FBFE6126F525E (item_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE decorations (id INT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(255) DEFAULT NULL, slot INT UNSIGNED NOT NULL, rarity INT UNSIGNED NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE decoration_skills (decoration_id INT UNSIGNED NOT NULL, skill_rank_id INT UNSIGNED NOT NULL, INDEX IDX_FE93F0BA3446DFC4 (decoration_id), INDEX IDX_FE93F0BA6CE3F9A6 (skill_rank_id), PRIMARY KEY(decoration_id, skill_rank_id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE ext_translations (id INT AUTO_INCREMENT NOT NULL, locale VARCHAR(8) NOT NULL, object_class VARCHAR(191) NOT NULL, field VARCHAR(32) NOT NULL, foreign_key VARCHAR(64) NOT NULL, content LONGTEXT DEFAULT NULL, INDEX translations_lookup_idx (locale, object_class, foreign_key), INDEX general_translations_lookup_idx (object_class, foreign_key), UNIQUE INDEX lookup_unique_idx (locale, object_class, field, foreign_key), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
			$this->addSql('CREATE TABLE horn_melodies (id INT UNSIGNED AUTO_INCREMENT NOT NULL, notes JSON NOT NULL COMMENT \'(DC2Type:json)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE horn_songs (id INT UNSIGNED AUTO_INCREMENT NOT NULL, melody_id INT UNSIGNED NOT NULL, sequence JSON NOT NULL COMMENT \'(DC2Type:json)\', duration INT UNSIGNED NOT NULL, effects VARCHAR(255) DEFAULT NULL, personal TINYINT(1) NOT NULL, INDEX IDX_168A3F76851F6525 (melody_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE items (id INT UNSIGNED AUTO_INCREMENT NOT NULL, rarity INT UNSIGNED NOT NULL, name VARCHAR(64) DEFAULT NULL, description LONGTEXT DEFAULT NULL, _value INT UNSIGNED NOT NULL, carry_limit INT UNSIGNED NOT NULL, UNIQUE INDEX UNIQ_E11EE94D5E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE locations (id INT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(255) DEFAULT NULL, zone_count INT UNSIGNED NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE monster_resistances (id INT UNSIGNED AUTO_INCREMENT NOT NULL, monster_id INT UNSIGNED DEFAULT NULL, _condition LONGTEXT DEFAULT NULL, kind VARCHAR(255) NOT NULL, element VARCHAR(255) DEFAULT NULL, status VARCHAR(255) DEFAULT NULL, INDEX IDX_7DE8A429C5FF1223 (monster_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE monster_reward_conditions (id INT UNSIGNED AUTO_INCREMENT NOT NULL, reward_id INT UNSIGNED DEFAULT NULL, kind VARCHAR(255) NOT NULL, rank VARCHAR(255) NOT NULL, quantity INT UNSIGNED NOT NULL, chance INT UNSIGNED NOT NULL, subtype VARCHAR(255) DEFAULT NULL, INDEX IDX_B134FDFDE466ACA1 (reward_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE monster_rewards (id INT UNSIGNED AUTO_INCREMENT NOT NULL, monster_id INT UNSIGNED DEFAULT NULL, item_id INT UNSIGNED DEFAULT NULL, INDEX IDX_4B43AF08C5FF1223 (monster_id), INDEX IDX_4B43AF08126F525E (item_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE monster_weaknesses (id INT UNSIGNED AUTO_INCREMENT NOT NULL, monster_id INT UNSIGNED DEFAULT NULL, level INT UNSIGNED NOT NULL, `condition` LONGTEXT DEFAULT NULL, kind VARCHAR(255) NOT NULL, element VARCHAR(255) DEFAULT NULL, status VARCHAR(255) DEFAULT NULL, INDEX IDX_1D01676C5FF1223 (monster_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE monsters (id INT UNSIGNED AUTO_INCREMENT NOT NULL, kind VARCHAR(255) NOT NULL, species VARCHAR(255) NOT NULL, name VARCHAR(255) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, elements JSON NOT NULL COMMENT \'(DC2Type:json)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE monster_ailments (monster_id INT UNSIGNED NOT NULL, ailment_id INT UNSIGNED NOT NULL, INDEX IDX_3F33B44C5FF1223 (monster_id), INDEX IDX_3F33B44432CD43A (ailment_id), PRIMARY KEY(monster_id, ailment_id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE monster_locations (monster_id INT UNSIGNED NOT NULL, location_id INT UNSIGNED NOT NULL, INDEX IDX_F35E41FDC5FF1223 (monster_id), INDEX IDX_F35E41FD64D218E (location_id), PRIMARY KEY(monster_id, location_id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE motion_values (id INT UNSIGNED AUTO_INCREMENT NOT NULL, weapon VARCHAR(255) NOT NULL, name VARCHAR(255) DEFAULT NULL, damage VARCHAR(255) NOT NULL, stun INT UNSIGNED NOT NULL, exhaust INT UNSIGNED NOT NULL, hits JSON NOT NULL COMMENT \'(DC2Type:json)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE rapid_fire (id INT UNSIGNED AUTO_INCREMENT NOT NULL, kind VARCHAR(255) NOT NULL, level INT UNSIGNED NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE sharpness (id INT UNSIGNED AUTO_INCREMENT NOT NULL, weapon_id INT UNSIGNED NOT NULL, red INT UNSIGNED NOT NULL, orange INT UNSIGNED NOT NULL, yellow INT UNSIGNED NOT NULL, green INT UNSIGNED NOT NULL, blue INT UNSIGNED NOT NULL, white INT UNSIGNED NOT NULL, purple INT UNSIGNED NOT NULL, INDEX IDX_E62BD8AC95B82273 (weapon_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE skill_ranks (id INT UNSIGNED AUTO_INCREMENT NOT NULL, skill_id INT UNSIGNED DEFAULT NULL, level INT UNSIGNED NOT NULL, description LONGTEXT DEFAULT NULL, INDEX IDX_EECE33285585C142 (skill_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE skills (id INT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE users (id INT UNSIGNED AUTO_INCREMENT NOT NULL, email_address VARCHAR(254) NOT NULL, password LONGTEXT DEFAULT NULL, roles JSON NOT NULL COMMENT \'(DC2Type:json)\', UNIQUE INDEX UNIQ_1483A5E9B08E074E (email_address), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE weapon_ammo (id INT UNSIGNED AUTO_INCREMENT NOT NULL, kind VARCHAR(255) NOT NULL, capacities JSON NOT NULL COMMENT \'(DC2Type:json)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE weapon_crafting (id INT UNSIGNED AUTO_INCREMENT NOT NULL, weapon_id INT UNSIGNED DEFAULT NULL, previous_id INT UNSIGNED DEFAULT NULL, craftable TINYINT(1) NOT NULL, crafting_zenny_cost INT UNSIGNED NOT NULL, upgrade_zenny_cost INT UNSIGNED NOT NULL, UNIQUE INDEX UNIQ_6F8C205E95B82273 (weapon_id), INDEX IDX_6F8C205E2DE62210 (previous_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE weapon_crafting_branches (weapon_crafting_id INT UNSIGNED NOT NULL, weapon_id INT UNSIGNED NOT NULL, INDEX IDX_C5251B471E92D4C (weapon_crafting_id), INDEX IDX_C5251B495B82273 (weapon_id), PRIMARY KEY(weapon_crafting_id, weapon_id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE weapon_crafting_costs (weapon_crafting_id INT UNSIGNED NOT NULL, material_cost_id INT UNSIGNED NOT NULL, INDEX IDX_3664782971E92D4C (weapon_crafting_id), INDEX IDX_36647829AC255ED0 (material_cost_id), PRIMARY KEY(weapon_crafting_id, material_cost_id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE weapon_crafting_upgrade_costs (weapon_crafting_id INT UNSIGNED NOT NULL, material_cost_id INT UNSIGNED NOT NULL, INDEX IDX_33949D571E92D4C (weapon_crafting_id), INDEX IDX_33949D5AC255ED0 (material_cost_id), PRIMARY KEY(weapon_crafting_id, material_cost_id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE weapon_specials (id INT UNSIGNED AUTO_INCREMENT NOT NULL, weapon_id INT UNSIGNED DEFAULT NULL, hidden TINYINT(1) NOT NULL, damage_raw INT UNSIGNED NOT NULL, damage_display INT UNSIGNED NOT NULL, kind VARCHAR(255) NOT NULL, element VARCHAR(255) DEFAULT NULL, status VARCHAR(255) DEFAULT NULL, INDEX IDX_5355A53F95B82273 (weapon_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE weapons (id INT UNSIGNED AUTO_INCREMENT NOT NULL, melody_id INT UNSIGNED DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, rarity INT NOT NULL, damage_kind VARCHAR(255) NOT NULL, defense_bonus INT UNSIGNED NOT NULL, elderseal VARCHAR(255) DEFAULT NULL, affinity INT UNSIGNED NOT NULL, slots JSON NOT NULL COMMENT \'(DC2Type:json)\', attack_raw INT UNSIGNED NOT NULL, attack_display INT UNSIGNED NOT NULL, kind VARCHAR(255) NOT NULL, shell VARCHAR(255) DEFAULT NULL, shell_level INT UNSIGNED DEFAULT NULL, coatings JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', deviation VARCHAR(255) DEFAULT NULL, special_ammo VARCHAR(255) DEFAULT NULL, INDEX IDX_520EBBE1851F6525 (melody_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE weapon_skills (weapon_id INT UNSIGNED NOT NULL, skill_id INT UNSIGNED NOT NULL, INDEX IDX_E8C4395795B82273 (weapon_id), INDEX IDX_E8C439575585C142 (skill_id), PRIMARY KEY(weapon_id, skill_id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE heavy_bowgun_ammo (heavy_bowgun_id INT UNSIGNED NOT NULL, ammo_id INT UNSIGNED NOT NULL, INDEX IDX_1B7A7365B3D3C464 (heavy_bowgun_id), INDEX IDX_1B7A73659F20CC20 (ammo_id), PRIMARY KEY(heavy_bowgun_id, ammo_id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE heavy_bowgun_auto_reload (heavy_bowgun_id INT UNSIGNED NOT NULL, auto_reload_id INT UNSIGNED NOT NULL, INDEX IDX_FD3283DB3D3C464 (heavy_bowgun_id), INDEX IDX_FD3283DB13121A6 (auto_reload_id), PRIMARY KEY(heavy_bowgun_id, auto_reload_id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE light_bowgun_ammo (light_bowgun_id INT UNSIGNED NOT NULL, ammo_id INT UNSIGNED NOT NULL, INDEX IDX_7AF5A029D029C12 (light_bowgun_id), INDEX IDX_7AF5A029F20CC20 (ammo_id), PRIMARY KEY(light_bowgun_id, ammo_id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE light_bowgun_auto_reload (light_bowgun_id INT UNSIGNED NOT NULL, auto_reload_id INT UNSIGNED NOT NULL, INDEX IDX_3ABB16A69D029C12 (light_bowgun_id), INDEX IDX_3ABB16A6B13121A6 (auto_reload_id), PRIMARY KEY(light_bowgun_id, auto_reload_id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('CREATE TABLE light_bowgun_rapid_fire (light_bowgun_id INT UNSIGNED NOT NULL, rapid_fire_id INT UNSIGNED NOT NULL, INDEX IDX_6091D3AE9D029C12 (light_bowgun_id), INDEX IDX_6091D3AEE9056C50 (rapid_fire_id), PRIMARY KEY(light_bowgun_id, rapid_fire_id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
			$this->addSql('ALTER TABLE ailment_protections ADD CONSTRAINT FK_6630DD52432CD43A FOREIGN KEY (ailment_id) REFERENCES ailments (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE ailment_protection_skills ADD CONSTRAINT FK_517E18BFFE812F5B FOREIGN KEY (ailment_protection_id) REFERENCES ailment_protections (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE ailment_protection_skills ADD CONSTRAINT FK_517E18BF5585C142 FOREIGN KEY (skill_id) REFERENCES skills (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE ailment_protection_item ADD CONSTRAINT FK_84E874CF1051F85E FOREIGN KEY (ailment_protection_items) REFERENCES ailment_protections (id)');
			$this->addSql('ALTER TABLE ailment_protection_item ADD CONSTRAINT FK_84E874CF126F525E FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE ailment_recoveries ADD CONSTRAINT FK_712E946B432CD43A FOREIGN KEY (ailment_id) REFERENCES ailments (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE ailment_recovery_items ADD CONSTRAINT FK_400DCBFE8B04118A FOREIGN KEY (ailment_recovery_id) REFERENCES ailment_recoveries (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE ailment_recovery_items ADD CONSTRAINT FK_400DCBFE126F525E FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE armor_crafting ADD CONSTRAINT FK_4BFD47B3F5AA3663 FOREIGN KEY (armor_id) REFERENCES armors (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE armor_crafting_costs ADD CONSTRAINT FK_5B6BF2EDDD6DD251 FOREIGN KEY (armor_crafting_id) REFERENCES armor_crafting (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE armor_crafting_costs ADD CONSTRAINT FK_5B6BF2EDAC255ED0 FOREIGN KEY (material_cost_id) REFERENCES crafting_material_costs (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE armor_set_bonus_ranks ADD CONSTRAINT FK_5DF784FC69545666 FOREIGN KEY (bonus_id) REFERENCES armor_set_bonuses (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE armor_set_bonus_ranks ADD CONSTRAINT FK_5DF784FC5585C142 FOREIGN KEY (skill_id) REFERENCES skill_ranks (id)');
			$this->addSql('ALTER TABLE armor_sets ADD CONSTRAINT FK_7C8A0B1069545666 FOREIGN KEY (bonus_id) REFERENCES armor_set_bonuses (id) ON DELETE SET NULL');
			$this->addSql('ALTER TABLE armors ADD CONSTRAINT FK_AFBA56C2537E6F87 FOREIGN KEY (armor_set_id) REFERENCES armor_sets (id) ON DELETE SET NULL');
			$this->addSql('ALTER TABLE armor_skills ADD CONSTRAINT FK_96B474EFF5AA3663 FOREIGN KEY (armor_id) REFERENCES armors (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE armor_skills ADD CONSTRAINT FK_96B474EF6CE3F9A6 FOREIGN KEY (skill_rank_id) REFERENCES skill_ranks (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE camps ADD CONSTRAINT FK_3D166BE564D218E FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE charm_rank_crafting ADD CONSTRAINT FK_15C9995D3BA5C9D1 FOREIGN KEY (charm_rank_id) REFERENCES charm_ranks (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE charm_rank_crafting_materials ADD CONSTRAINT FK_AC58A140401E3381 FOREIGN KEY (charm_rank_crafting_id) REFERENCES charm_rank_crafting (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE charm_rank_crafting_materials ADD CONSTRAINT FK_AC58A140AC255ED0 FOREIGN KEY (material_cost_id) REFERENCES crafting_material_costs (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE charm_ranks ADD CONSTRAINT FK_DF91C65593E9261F FOREIGN KEY (charm_id) REFERENCES charms (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE charm_rank_skills ADD CONSTRAINT FK_6413356B3BA5C9D1 FOREIGN KEY (charm_rank_id) REFERENCES charm_ranks (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE charm_rank_skills ADD CONSTRAINT FK_6413356B6CE3F9A6 FOREIGN KEY (skill_rank_id) REFERENCES skill_ranks (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE crafting_material_costs ADD CONSTRAINT FK_1B8FBFE6126F525E FOREIGN KEY (item_id) REFERENCES items (id)');
			$this->addSql('ALTER TABLE decoration_skills ADD CONSTRAINT FK_FE93F0BA3446DFC4 FOREIGN KEY (decoration_id) REFERENCES decorations (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE decoration_skills ADD CONSTRAINT FK_FE93F0BA6CE3F9A6 FOREIGN KEY (skill_rank_id) REFERENCES skill_ranks (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE horn_songs ADD CONSTRAINT FK_168A3F76851F6525 FOREIGN KEY (melody_id) REFERENCES horn_melodies (id)');
			$this->addSql('ALTER TABLE monster_resistances ADD CONSTRAINT FK_7DE8A429C5FF1223 FOREIGN KEY (monster_id) REFERENCES monsters (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE monster_reward_conditions ADD CONSTRAINT FK_B134FDFDE466ACA1 FOREIGN KEY (reward_id) REFERENCES monster_rewards (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE monster_rewards ADD CONSTRAINT FK_4B43AF08C5FF1223 FOREIGN KEY (monster_id) REFERENCES monsters (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE monster_rewards ADD CONSTRAINT FK_4B43AF08126F525E FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE monster_weaknesses ADD CONSTRAINT FK_1D01676C5FF1223 FOREIGN KEY (monster_id) REFERENCES monsters (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE monster_ailments ADD CONSTRAINT FK_3F33B44C5FF1223 FOREIGN KEY (monster_id) REFERENCES monsters (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE monster_ailments ADD CONSTRAINT FK_3F33B44432CD43A FOREIGN KEY (ailment_id) REFERENCES ailments (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE monster_locations ADD CONSTRAINT FK_F35E41FDC5FF1223 FOREIGN KEY (monster_id) REFERENCES monsters (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE monster_locations ADD CONSTRAINT FK_F35E41FD64D218E FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE sharpness ADD CONSTRAINT FK_E62BD8AC95B82273 FOREIGN KEY (weapon_id) REFERENCES weapons (id)');
			$this->addSql('ALTER TABLE skill_ranks ADD CONSTRAINT FK_EECE33285585C142 FOREIGN KEY (skill_id) REFERENCES skills (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE weapon_crafting ADD CONSTRAINT FK_6F8C205E95B82273 FOREIGN KEY (weapon_id) REFERENCES weapons (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE weapon_crafting ADD CONSTRAINT FK_6F8C205E2DE62210 FOREIGN KEY (previous_id) REFERENCES weapons (id) ON DELETE SET NULL');
			$this->addSql('ALTER TABLE weapon_crafting_branches ADD CONSTRAINT FK_C5251B471E92D4C FOREIGN KEY (weapon_crafting_id) REFERENCES weapon_crafting (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE weapon_crafting_branches ADD CONSTRAINT FK_C5251B495B82273 FOREIGN KEY (weapon_id) REFERENCES weapons (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE weapon_crafting_costs ADD CONSTRAINT FK_3664782971E92D4C FOREIGN KEY (weapon_crafting_id) REFERENCES weapon_crafting (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE weapon_crafting_costs ADD CONSTRAINT FK_36647829AC255ED0 FOREIGN KEY (material_cost_id) REFERENCES crafting_material_costs (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE weapon_crafting_upgrade_costs ADD CONSTRAINT FK_33949D571E92D4C FOREIGN KEY (weapon_crafting_id) REFERENCES weapon_crafting (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE weapon_crafting_upgrade_costs ADD CONSTRAINT FK_33949D5AC255ED0 FOREIGN KEY (material_cost_id) REFERENCES crafting_material_costs (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE weapon_specials ADD CONSTRAINT FK_5355A53F95B82273 FOREIGN KEY (weapon_id) REFERENCES weapons (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE weapons ADD CONSTRAINT FK_520EBBE1851F6525 FOREIGN KEY (melody_id) REFERENCES horn_melodies (id)');
			$this->addSql('ALTER TABLE weapon_skills ADD CONSTRAINT FK_E8C4395795B82273 FOREIGN KEY (weapon_id) REFERENCES weapons (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE weapon_skills ADD CONSTRAINT FK_E8C439575585C142 FOREIGN KEY (skill_id) REFERENCES skills (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE heavy_bowgun_ammo ADD CONSTRAINT FK_1B7A7365B3D3C464 FOREIGN KEY (heavy_bowgun_id) REFERENCES weapons (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE heavy_bowgun_ammo ADD CONSTRAINT FK_1B7A73659F20CC20 FOREIGN KEY (ammo_id) REFERENCES weapon_ammo (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE heavy_bowgun_auto_reload ADD CONSTRAINT FK_FD3283DB3D3C464 FOREIGN KEY (heavy_bowgun_id) REFERENCES weapons (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE heavy_bowgun_auto_reload ADD CONSTRAINT FK_FD3283DB13121A6 FOREIGN KEY (auto_reload_id) REFERENCES auto_reload (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE light_bowgun_ammo ADD CONSTRAINT FK_7AF5A029D029C12 FOREIGN KEY (light_bowgun_id) REFERENCES weapons (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE light_bowgun_ammo ADD CONSTRAINT FK_7AF5A029F20CC20 FOREIGN KEY (ammo_id) REFERENCES weapon_ammo (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE light_bowgun_auto_reload ADD CONSTRAINT FK_3ABB16A69D029C12 FOREIGN KEY (light_bowgun_id) REFERENCES weapons (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE light_bowgun_auto_reload ADD CONSTRAINT FK_3ABB16A6B13121A6 FOREIGN KEY (auto_reload_id) REFERENCES auto_reload (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE light_bowgun_rapid_fire ADD CONSTRAINT FK_6091D3AE9D029C12 FOREIGN KEY (light_bowgun_id) REFERENCES weapons (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE light_bowgun_rapid_fire ADD CONSTRAINT FK_6091D3AEE9056C50 FOREIGN KEY (rapid_fire_id) REFERENCES rapid_fire (id) ON DELETE CASCADE');
			// @formatter:on
		}

		public function down(Schema $schema): void {
			$this->addSql('ALTER TABLE ailment_protections DROP FOREIGN KEY FK_6630DD52432CD43A');
			$this->addSql('ALTER TABLE ailment_protection_skills DROP FOREIGN KEY FK_517E18BFFE812F5B');
			$this->addSql('ALTER TABLE ailment_protection_skills DROP FOREIGN KEY FK_517E18BF5585C142');
			$this->addSql('ALTER TABLE ailment_protection_item DROP FOREIGN KEY FK_84E874CF1051F85E');
			$this->addSql('ALTER TABLE ailment_protection_item DROP FOREIGN KEY FK_84E874CF126F525E');
			$this->addSql('ALTER TABLE ailment_recoveries DROP FOREIGN KEY FK_712E946B432CD43A');
			$this->addSql('ALTER TABLE ailment_recovery_items DROP FOREIGN KEY FK_400DCBFE8B04118A');
			$this->addSql('ALTER TABLE ailment_recovery_items DROP FOREIGN KEY FK_400DCBFE126F525E');
			$this->addSql('ALTER TABLE armor_crafting DROP FOREIGN KEY FK_4BFD47B3F5AA3663');
			$this->addSql('ALTER TABLE armor_crafting_costs DROP FOREIGN KEY FK_5B6BF2EDDD6DD251');
			$this->addSql('ALTER TABLE armor_crafting_costs DROP FOREIGN KEY FK_5B6BF2EDAC255ED0');
			$this->addSql('ALTER TABLE armor_set_bonus_ranks DROP FOREIGN KEY FK_5DF784FC69545666');
			$this->addSql('ALTER TABLE armor_set_bonus_ranks DROP FOREIGN KEY FK_5DF784FC5585C142');
			$this->addSql('ALTER TABLE armor_sets DROP FOREIGN KEY FK_7C8A0B1069545666');
			$this->addSql('ALTER TABLE armors DROP FOREIGN KEY FK_AFBA56C2537E6F87');
			$this->addSql('ALTER TABLE armor_skills DROP FOREIGN KEY FK_96B474EFF5AA3663');
			$this->addSql('ALTER TABLE armor_skills DROP FOREIGN KEY FK_96B474EF6CE3F9A6');
			$this->addSql('ALTER TABLE camps DROP FOREIGN KEY FK_3D166BE564D218E');
			$this->addSql('ALTER TABLE charm_rank_crafting DROP FOREIGN KEY FK_15C9995D3BA5C9D1');
			$this->addSql('ALTER TABLE charm_rank_crafting_materials DROP FOREIGN KEY FK_AC58A140401E3381');
			$this->addSql('ALTER TABLE charm_rank_crafting_materials DROP FOREIGN KEY FK_AC58A140AC255ED0');
			$this->addSql('ALTER TABLE charm_ranks DROP FOREIGN KEY FK_DF91C65593E9261F');
			$this->addSql('ALTER TABLE charm_rank_skills DROP FOREIGN KEY FK_6413356B3BA5C9D1');
			$this->addSql('ALTER TABLE charm_rank_skills DROP FOREIGN KEY FK_6413356B6CE3F9A6');
			$this->addSql('ALTER TABLE crafting_material_costs DROP FOREIGN KEY FK_1B8FBFE6126F525E');
			$this->addSql('ALTER TABLE decoration_skills DROP FOREIGN KEY FK_FE93F0BA3446DFC4');
			$this->addSql('ALTER TABLE decoration_skills DROP FOREIGN KEY FK_FE93F0BA6CE3F9A6');
			$this->addSql('ALTER TABLE horn_songs DROP FOREIGN KEY FK_168A3F76851F6525');
			$this->addSql('ALTER TABLE monster_resistances DROP FOREIGN KEY FK_7DE8A429C5FF1223');
			$this->addSql('ALTER TABLE monster_reward_conditions DROP FOREIGN KEY FK_B134FDFDE466ACA1');
			$this->addSql('ALTER TABLE monster_rewards DROP FOREIGN KEY FK_4B43AF08C5FF1223');
			$this->addSql('ALTER TABLE monster_rewards DROP FOREIGN KEY FK_4B43AF08126F525E');
			$this->addSql('ALTER TABLE monster_weaknesses DROP FOREIGN KEY FK_1D01676C5FF1223');
			$this->addSql('ALTER TABLE monster_ailments DROP FOREIGN KEY FK_3F33B44C5FF1223');
			$this->addSql('ALTER TABLE monster_ailments DROP FOREIGN KEY FK_3F33B44432CD43A');
			$this->addSql('ALTER TABLE monster_locations DROP FOREIGN KEY FK_F35E41FDC5FF1223');
			$this->addSql('ALTER TABLE monster_locations DROP FOREIGN KEY FK_F35E41FD64D218E');
			$this->addSql('ALTER TABLE sharpness DROP FOREIGN KEY FK_E62BD8AC95B82273');
			$this->addSql('ALTER TABLE skill_ranks DROP FOREIGN KEY FK_EECE33285585C142');
			$this->addSql('ALTER TABLE weapon_crafting DROP FOREIGN KEY FK_6F8C205E95B82273');
			$this->addSql('ALTER TABLE weapon_crafting DROP FOREIGN KEY FK_6F8C205E2DE62210');
			$this->addSql('ALTER TABLE weapon_crafting_branches DROP FOREIGN KEY FK_C5251B471E92D4C');
			$this->addSql('ALTER TABLE weapon_crafting_branches DROP FOREIGN KEY FK_C5251B495B82273');
			$this->addSql('ALTER TABLE weapon_crafting_costs DROP FOREIGN KEY FK_3664782971E92D4C');
			$this->addSql('ALTER TABLE weapon_crafting_costs DROP FOREIGN KEY FK_36647829AC255ED0');
			$this->addSql('ALTER TABLE weapon_crafting_upgrade_costs DROP FOREIGN KEY FK_33949D571E92D4C');
			$this->addSql('ALTER TABLE weapon_crafting_upgrade_costs DROP FOREIGN KEY FK_33949D5AC255ED0');
			$this->addSql('ALTER TABLE weapon_specials DROP FOREIGN KEY FK_5355A53F95B82273');
			$this->addSql('ALTER TABLE weapons DROP FOREIGN KEY FK_520EBBE1851F6525');
			$this->addSql('ALTER TABLE weapon_skills DROP FOREIGN KEY FK_E8C4395795B82273');
			$this->addSql('ALTER TABLE weapon_skills DROP FOREIGN KEY FK_E8C439575585C142');
			$this->addSql('ALTER TABLE heavy_bowgun_ammo DROP FOREIGN KEY FK_1B7A7365B3D3C464');
			$this->addSql('ALTER TABLE heavy_bowgun_ammo DROP FOREIGN KEY FK_1B7A73659F20CC20');
			$this->addSql('ALTER TABLE heavy_bowgun_auto_reload DROP FOREIGN KEY FK_FD3283DB3D3C464');
			$this->addSql('ALTER TABLE heavy_bowgun_auto_reload DROP FOREIGN KEY FK_FD3283DB13121A6');
			$this->addSql('ALTER TABLE light_bowgun_ammo DROP FOREIGN KEY FK_7AF5A029D029C12');
			$this->addSql('ALTER TABLE light_bowgun_ammo DROP FOREIGN KEY FK_7AF5A029F20CC20');
			$this->addSql('ALTER TABLE light_bowgun_auto_reload DROP FOREIGN KEY FK_3ABB16A69D029C12');
			$this->addSql('ALTER TABLE light_bowgun_auto_reload DROP FOREIGN KEY FK_3ABB16A6B13121A6');
			$this->addSql('ALTER TABLE light_bowgun_rapid_fire DROP FOREIGN KEY FK_6091D3AE9D029C12');
			$this->addSql('ALTER TABLE light_bowgun_rapid_fire DROP FOREIGN KEY FK_6091D3AEE9056C50');
			$this->addSql('DROP TABLE ailment_protections');
			$this->addSql('DROP TABLE ailment_protection_skills');
			$this->addSql('DROP TABLE ailment_protection_item');
			$this->addSql('DROP TABLE ailment_recoveries');
			$this->addSql('DROP TABLE ailment_recovery_items');
			$this->addSql('DROP TABLE ailments');
			$this->addSql('DROP TABLE armor_crafting');
			$this->addSql('DROP TABLE armor_crafting_costs');
			$this->addSql('DROP TABLE armor_set_bonus_ranks');
			$this->addSql('DROP TABLE armor_set_bonuses');
			$this->addSql('DROP TABLE armor_sets');
			$this->addSql('DROP TABLE armors');
			$this->addSql('DROP TABLE armor_skills');
			$this->addSql('DROP TABLE auto_reload');
			$this->addSql('DROP TABLE camps');
			$this->addSql('DROP TABLE charm_rank_crafting');
			$this->addSql('DROP TABLE charm_rank_crafting_materials');
			$this->addSql('DROP TABLE charm_ranks');
			$this->addSql('DROP TABLE charm_rank_skills');
			$this->addSql('DROP TABLE charms');
			$this->addSql('DROP TABLE crafting_material_costs');
			$this->addSql('DROP TABLE decorations');
			$this->addSql('DROP TABLE decoration_skills');
			$this->addSql('DROP TABLE ext_translations');
			$this->addSql('DROP TABLE horn_melodies');
			$this->addSql('DROP TABLE horn_songs');
			$this->addSql('DROP TABLE items');
			$this->addSql('DROP TABLE locations');
			$this->addSql('DROP TABLE monster_resistances');
			$this->addSql('DROP TABLE monster_reward_conditions');
			$this->addSql('DROP TABLE monster_rewards');
			$this->addSql('DROP TABLE monster_weaknesses');
			$this->addSql('DROP TABLE monsters');
			$this->addSql('DROP TABLE monster_ailments');
			$this->addSql('DROP TABLE monster_locations');
			$this->addSql('DROP TABLE motion_values');
			$this->addSql('DROP TABLE rapid_fire');
			$this->addSql('DROP TABLE sharpness');
			$this->addSql('DROP TABLE skill_ranks');
			$this->addSql('DROP TABLE skills');
			$this->addSql('DROP TABLE users');
			$this->addSql('DROP TABLE weapon_ammo');
			$this->addSql('DROP TABLE weapon_crafting');
			$this->addSql('DROP TABLE weapon_crafting_branches');
			$this->addSql('DROP TABLE weapon_crafting_costs');
			$this->addSql('DROP TABLE weapon_crafting_upgrade_costs');
			$this->addSql('DROP TABLE weapon_specials');
			$this->addSql('DROP TABLE weapons');
			$this->addSql('DROP TABLE weapon_skills');
			$this->addSql('DROP TABLE heavy_bowgun_ammo');
			$this->addSql('DROP TABLE heavy_bowgun_auto_reload');
			$this->addSql('DROP TABLE light_bowgun_ammo');
			$this->addSql('DROP TABLE light_bowgun_auto_reload');
			$this->addSql('DROP TABLE light_bowgun_rapid_fire');
		}
	}
