controllers:
    type: attribute
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    defaults:
        _format: json

dbstudios_rest.crud:
    resource: dbstudios_rest.crud.route_loader
    type: service
    defaults:
        _format: json
        _locale: en

auth.login:
    path: /auth

_extra_routes:
    resource: './routes'
    type: 'directory'
